#!/usr/bin/env bash
# scripts/dev-up.sh — single-command local Supabase dev orchestration
#
# Usage:
#   bash scripts/dev-up.sh                   # localhost-only (safe default)
#   WITH_LAN_ACCESS=1 bash scripts/dev-up.sh # bind to LAN IP for physical-device testing
#   WITH_EXTRACTION=1 bash scripts/dev-up.sh # also start cloud-run/extraction-service in dev mode
#
# What it does:
#   1. Verify Docker is running (Supabase CLI dependency)
#   2. supabase start — boots the local stack (Postgres, GoTrue, Storage, Studio, Inbucket, Edge runtime)
#   3. Apply migrations + seed.sql (db reset)
#   4. Capture auto-generated anon/service keys → write rn-app/.env.local + admin-app/.env.local
#   5. Start `supabase functions serve` in background reading supabase/.env.local
#   6. Optionally start the Cloud Run extraction-service locally
#   7. Print a summary table of URLs
#
# Security defaults:
#   - Binds to 127.0.0.1 only by default. Phones on the same wifi cannot reach your local Supabase.
#   - When WITH_LAN_ACCESS=1, prints a clear warning and binds to the LAN IP so a physical device can reach it.
#     A real Supabase service-role key is auto-generated by `supabase start` regardless of LAN flag,
#     but you should still avoid running this on hostile networks (coffee shops) — use USB tether or hotspot.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# Pretty printing
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

# ─── 1. Docker preflight ─────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  echo -e "${RED}✗ Docker is not installed.${NC}"
  echo "  Install Docker Desktop (https://www.docker.com/products/docker-desktop/)"
  echo "  or OrbStack (https://orbstack.dev) — both work."
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  echo -e "${RED}✗ Docker daemon is not running.${NC}"
  echo "  Start Docker Desktop / OrbStack and re-run this script."
  exit 1
fi
echo -e "${GREEN}✓ Docker is running${NC}"

# ─── 2. Determine bind address ───────────────────────────────────────────────
HOST="127.0.0.1"
if [[ "${WITH_LAN_ACCESS:-}" == "1" ]]; then
  # Try to find LAN IP (macOS: en0 wifi, fallback to hostname -I on Linux)
  if [[ "$(uname)" == "Darwin" ]]; then
    HOST="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo 127.0.0.1)"
  else
    HOST="$(hostname -I 2>/dev/null | awk '{print $1}' || echo 127.0.0.1)"
  fi
  if [[ "$HOST" == "127.0.0.1" ]]; then
    echo -e "${YELLOW}! Could not determine LAN IP; falling back to 127.0.0.1${NC}"
  else
    echo -e "${YELLOW}! WITH_LAN_ACCESS=1 — binding rn-app/.env.local to ${HOST}${NC}"
    echo -e "${YELLOW}  Anyone on the same network can reach your local Supabase. Avoid hostile networks.${NC}"
  fi
fi

# ─── 3. Start Supabase ───────────────────────────────────────────────────────
echo -e "${CYAN}→ Starting Supabase…${NC}"
supabase start

# ─── 4. Capture keys ─────────────────────────────────────────────────────────
STATUS_JSON="$(supabase status -o json 2>/dev/null || echo '{}')"
ANON_KEY="$(echo "$STATUS_JSON" | grep -oE '"ANON_KEY"\s*:\s*"[^"]+"' | head -1 | sed -E 's/.*"([^"]+)"$/\1/')"
SERVICE_KEY="$(echo "$STATUS_JSON" | grep -oE '"SERVICE_ROLE_KEY"\s*:\s*"[^"]+"' | head -1 | sed -E 's/.*"([^"]+)"$/\1/')"

if [[ -z "$ANON_KEY" || -z "$SERVICE_KEY" ]]; then
  # Fallback: parse `supabase status` text output
  ANON_KEY="$(supabase status 2>/dev/null | awk -F': *' '/anon key/{print $2; exit}')"
  SERVICE_KEY="$(supabase status 2>/dev/null | awk -F': *' '/service_role key/{print $2; exit}')"
fi

if [[ -z "$ANON_KEY" || -z "$SERVICE_KEY" ]]; then
  echo -e "${RED}✗ Could not parse anon/service keys from supabase status. Run \`supabase status\` manually.${NC}"
  exit 1
fi

# ─── 5. Apply migrations + seed (idempotent) ─────────────────────────────────
echo -e "${CYAN}→ Resetting + reseeding local DB…${NC}"
supabase db reset --no-seed=false

# ─── 6. Write rn-app/.env.local ──────────────────────────────────────────────
RN_ENV="$ROOT/rn-app/.env.local"
cat > "$RN_ENV" <<EOF
# AUTO-GENERATED by scripts/dev-up.sh — re-running the script will overwrite.
# To preserve overrides across regenerations, set them in your shell instead.
APP_ENV=development
EXPO_PUBLIC_SUPABASE_URL=http://${HOST}:54321
EXPO_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
EXPO_PUBLIC_PAYMENT_GATEWAY=cashfree
EXPO_PUBLIC_CASHFREE_ENV=SANDBOX
EXPO_PUBLIC_USE_OTP_ROUTING=false
EOF
echo -e "${GREEN}✓ Wrote ${RN_ENV}${NC}"

# ─── 7. Write admin-app/.env.local ───────────────────────────────────────────
ADMIN_ENV="$ROOT/admin-app/.env.local"
cat > "$ADMIN_ENV" <<EOF
# AUTO-GENERATED by scripts/dev-up.sh — local-Supabase config for the admin app.
# Re-running the script overwrites this file. Personal overrides → use shell env.
NEXT_PUBLIC_SUPABASE_URL=http://${HOST}:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
NEXT_PUBLIC_ADMIN_KEY=local-admin-key-please-rotate
EOF
echo -e "${GREEN}✓ Wrote ${ADMIN_ENV}${NC}"

# ─── 8. Optionally start extraction service ─────────────────────────────────
EXTRACTION_PID=""
if [[ "${WITH_EXTRACTION:-}" == "1" ]]; then
  if [[ ! -f "$ROOT/cloud-run/extraction-service/.env.local" ]]; then
    echo -e "${YELLOW}! cloud-run/extraction-service/.env.local missing.${NC}"
    echo "  Copy from cloud-run/extraction-service/.env.local.example and fill in your test creds."
    echo "  Skipping extraction-service start."
  else
    echo -e "${CYAN}→ Starting cloud-run/extraction-service in dev mode…${NC}"
    (cd "$ROOT/cloud-run/extraction-service" && npm run dev) &
    EXTRACTION_PID=$!
  fi
fi

# ─── 9. Edge functions serve (foreground) ────────────────────────────────────
ENV_FILE="$ROOT/supabase/.env.local"
if [[ ! -f "$ENV_FILE" ]]; then
  echo -e "${YELLOW}! supabase/.env.local missing — copy from supabase/.env.local.example and fill in test creds${NC}"
  echo "  Edge functions will start but Cashfree/Twilio/Gemini calls will fail until you populate the file."
  ENV_FILE_FLAG=""
else
  ENV_FILE_FLAG="--env-file $ENV_FILE"
fi

echo ""
echo "════════════════════════════════════════════════════════════════════"
echo -e "${GREEN}Local Supabase ready.${NC}"
echo "  API:           http://${HOST}:54321"
echo "  Studio:        http://127.0.0.1:54323"
echo "  DB:            postgresql://postgres:postgres@127.0.0.1:54322/postgres"
echo "  Inbucket:      http://127.0.0.1:54324  (catch-all email + SMS for OTP)"
[[ -n "${EXTRACTION_PID}" ]] && echo "  Extraction:    http://127.0.0.1:8080"
echo ""
echo "  Test phones: +919999900001, +919999900002, +919999900003 (OTP: 123456 or check Inbucket)"
echo ""
echo -e "${CYAN}Next: cd rn-app && npx expo start${NC}"
echo "════════════════════════════════════════════════════════════════════"
echo ""
echo -e "${CYAN}→ Starting edge function runtime in foreground (Ctrl-C to stop everything)…${NC}"

# Trap to clean up extraction service on exit
trap 'if [[ -n "${EXTRACTION_PID}" ]]; then kill "${EXTRACTION_PID}" 2>/dev/null || true; fi' EXIT

# shellcheck disable=SC2086
supabase functions serve $ENV_FILE_FLAG
